# Generated by Django 4.2.1 on 2023-05-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=250, verbose_name='название филиала')),
                ('latitude', models.CharField(max_length=300, verbose_name='широта')),
                ('longitude', models.CharField(max_length=300, verbose_name='долгота')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=250, verbose_name='номер телефона')),
                ('chat_id', models.IntegerField(blank=True, null=True, verbose_name='ID телеграм чата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_position', models.CharField(blank=True, max_length=300, null=True, verbose_name='должность')),
                ('request_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='тип заявки')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='дата начала периода')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='дата окончания периода')),
                ('shift_date', models.DateField(blank=True, null=True, verbose_name='дата смены')),
                ('shift_time_start', models.CharField(blank=True, max_length=150, null=True, verbose_name='время начала смены')),
                ('shift_time_end', models.CharField(blank=True, max_length=150, null=True, verbose_name='время окончания смены')),
                ('number_of_employees', models.CharField(blank=True, max_length=3, null=True, verbose_name='количество сотрудников')),
                ('request_comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='telegram_bot.branch')),
            ],
            options={
                'verbose_name': 'Заявка на сотрудников',
                'verbose_name_plural': 'Заявки на сотрудников',
            },
        ),
        migrations.CreateModel(
            name='JobRequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='telegram_bot.employee', verbose_name='сотрудник')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='telegram_bot.jobrequest', verbose_name='заявка на сотрудника')),
            ],
            options={
                'verbose_name': 'Назначение сотрудников',
                'verbose_name_plural': 'Назначения сотрудников',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGeoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=300, verbose_name='широта')),
                ('longitude', models.CharField(max_length=300, verbose_name='долгота')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_positions', to='telegram_bot.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'Геопозиция сотрудника',
                'verbose_name_plural': 'Геопозиция сотрудников',
            },
        ),
    ]
