# Generated by Django 4.2.1 on 2023-05-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_position', models.CharField(blank=True, max_length=300, null=True, verbose_name='должность')),
                ('request_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='тип заявки')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='дата начала периода')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='дата окончания периода')),
                ('shift_date', models.DateField(blank=True, null=True, verbose_name='дата смены')),
                ('shift_hours', models.DateTimeField(blank=True, null=True, verbose_name='время смены')),
                ('number_of_employees', models.CharField(blank=True, max_length=3, null=True, verbose_name='количество сотрудников')),
                ('request_comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Заявка на сотрудников',
                'verbose_name_plural': 'Заявки на сотрудников',
            },
        ),
        migrations.RenameField(
            model_name='employeegeoposition',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameModel(
            old_name='BranchGeoPosition',
            new_name='Branch',
        ),
        migrations.CreateModel(
            name='JobRequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='telegram_bot.employee')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='telegram_bot.jobrequest')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='telegram_bot.branch'),
        ),
    ]
