# Generated by Django 4.2.1 on 2023-05-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequestassignment',
            name='end_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_assignments', to='telegram_bot.employeegeoposition', verbose_name='окончание смены'),
        ),
        migrations.AddField(
            model_name='jobrequestassignment',
            name='start_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_assignments', to='telegram_bot.employeegeoposition', verbose_name='начало смены'),
        ),
    ]
