# Generated by Django 4.2.1 on 2023-05-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_remove_jobrequestassignment_end_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название компании')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='message_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст рассылки'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='request_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата заявки'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Принята'), ('REJECTED', 'Отклонена'), ('CANCELED', 'Отменена'), ('CLOSED', 'Закрыта')], max_length=250, null=True, verbose_name='статус заявки'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brances', to='telegram_bot.company', verbose_name='компания'),
        ),
    ]
