# Generated by Django 4.2.1 on 2023-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_jobrequestassignment_end_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequestassignment',
            name='assignment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
