# Generated by Django 4.2.1 on 2023-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_jobrequestassignment_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequestassignment',
            name='assignment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
