# Generated by Django 4.2.1 on 2023-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_jobrequestassignment_assignment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='shift_date',
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='shift_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='время окончания смены'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='shift_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='время начала смены'),
        ),
    ]
