# Generated by Django 4.2.1 on 2023-05-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_date',
            field=models.DateField(auto_now=True, verbose_name='дата смены'),
        ),
    ]
