# Generated by Django 4.2.1 on 2023-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_remove_jobrequest_shift_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegeoposition',
            name='geo_positions_date',
            field=models.DateField(auto_now=True, verbose_name='дата внесения гео позиций'),
        ),
        migrations.AlterField(
            model_name='jobrequestassignment',
            name='assignment_date',
            field=models.DateField(auto_now=True, verbose_name='дата назначения'),
        ),
    ]
