# Generated by Django 4.2.1 on 2023-05-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_alter_shift_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='last_notified_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата последнего уведомления'),
        ),
    ]
